services:
  feldspar:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: feldspar-dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - feldspar_node_modules:/app/packages/feldspar/node_modules
      - feldspar_dists:/app/packages/feldspar/dists
      - data_collector_node_modules:/app/packages/data-collector/node_modules
    command: sh -c "npm install && npm run start"
volumes:
  node_modules: {}
  feldspar_node_modules: {}
  feldspar_dists: {}
  data_collector_node_modules: {}